### ISSUE TITLE
ICS 3: IBC connection lifecycle, protocol negotation handshake

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#3]
Primarily a port of [the connection section of the original IBC spec](https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/ibc/connections.md).

Will cover:
- IBC connection data structure
- Possible states of an IBC connection
- IBC connection management packet handling state machine
- Wire encoding formats for IBC connection management (metadata) packets
- Description of initial datagram ("OPENTRY")
- Description of response datagram ("OPENACK")
- Description of confirmation datagram ("OPENCONFIRM")
- Algorithms for handling all datagrams
- Format for option transmission from opening chain to destination chain

**Comment by mossid** [comment]
Attack vector:
Consider chain `S`, `D`, `D'`. In permissionless chain registration, a malicious entity can register `ROT_S` to both `D` and `D'`, while registering `ROT_D` on `S`. This makes that both chain `D` and `D'` believe that they are bidirectionally connected with `S`, but in fact only `D` is. While the connection between `S` and `D` works normally, the packet sent from `D'` cannot reach to `S`. It is not a problem if the packet is controlled by an EOA, but if there is a fully automatic logic on a chain, for example, a contract, it does not have external information outside of the chain's observation, so it follows the belief of `D'`. All packet sent from `D'` is lost, but since the packet index of `S` is increasing(because of the packets coming from `D`), the timeout logic doesn't work so `D'` cannot recover from it.

**Comment by cwgoes** [comment]
To-do in spec:
- Clearly reference consensus primitives defined in ICS 2
- Define state of connection which must be kept in store as a struct
- Define basic options on connection
- Define protocol negotiation handshake, pseudocode algorithms
- Enumerate security guarantees

**Comment by cwgoes** [comment]
Eventually we may want unidirectional connections, but I think I will focus on bidirectional handshake design first since that seems like the harder problem - easier to simplify later.

**Comment by cwgoes** [comment]
Datagram formats that need to be defined here:

Opening handshake:

- `OPENTRY` - try to open a connection
- `OPENACK` - acknowledge a connection
- `OPENCONFIRM` - finalize a connection (iff we need a three-way handshake)

"Safe" closing handshake:

- `CLOSETRY` - try to close a connection
- `CLOSEACK` - acknowledge a connection close

Fraud proofs (or referenced):

- `CLOSEFRAUD` - close a connection with proof-of-double-sign

**Comment by cwgoes** [comment]
Subprotocols that need to be defined here:

- Connection opening handshake
- Consensus transcript tracking
- Connection closing handshake

**Comment by cwgoes** [comment]
Data structures that need to be defined here:

- Connection
- Datagram (high-level)
- Datagrams for subprotocols

**Comment by cwgoes** [comment]
Note: may need to store last `n` headers to prevent race conditions on accumulator proofs.
