### ISSUE TITLE
ICS ?: Transient Queue

### ISSUE THREAD

**Issue by mossid** [cosmos/ics#41]
Will cover:
* Requirements for non-persisting queue

**Comment by cwgoes** [comment]
Can you clarify how this differs from https://github.com/cosmos/ics/issues/39 - what will a transient queue be used for?

**Comment by mossid** [comment]
We can define a standard queue as a restricted form of a transient queue. On the transient queue, there is no restriction about the state persistence. A packet could be stored on a block but the properties do not guarantee that the blocks after that will also contain the packet. This means we cannot batch process the packets (via range proofs) on a transient queue. - the verifier chain should store every block where the packets are pushed on. This can be used for the pegzones, where we (mostly) don't take advantage from batch processing(e.g. merkle Patricia tree) also we cannot skip the blocks anyway.

Standard queues share same properties with transient queues except that there is one more that, if a block does not contain a cleanup event(or any other pruning event), then it should contain all of the packets of the previous chain. With this property, we can prove that even a chain skips the block arbitrary it is still ensured that the chain can receive all the packets from the other.

**Comment by cwgoes** [comment]
I see; that distinction does sound useful, although I'm still not sure it warrants a separate ICS instead of a subsection of #39 and an alternative update algorithm for processing packets committed by transient queues (which cannot skip blocks).

In fact, I wonder if a further category of "temporary queue", which guarantees that packets will be kept for some `k` blocks but no longer, would also be useful, to allow skipping most blocks but requiring at least one every `k`.

**Comment by cwgoes** [comment]
@mossid Do you think we still need this, now that we store succinct commitments to packet data and just keep sequence numbers instead of a full queue?

**Comment by cwgoes** [comment]
Closing, but reopen if this is still necessary for some reason.
