### ISSUE TITLE
A public group to discuss all things IBC 

### ISSUE THREAD

**Issue by vshvsh** [cosmos/ics#58]
I think we might want to have a public place for quick and dirty discussions of IBC proposals, process etc. Some of that already happens in a private Slack channel of Tendermint (i.e. https://github.com/cosmos/ics/issues/23#issuecomment-471070014) which is fine now but not in the future when IBC specs are essential for non-tendermint blockchains.

**Comment by cwgoes** [comment]
I agree that discussion and specification of IBC should be done in public with an open process and documented reasoning / decisionmaking.

This ICS repo is intended to be that public discussion forum; we're trying to avoid internal-only communication channels (and will be recording Zoom meetings, which are generally open to interested parties) - I am a bit hesitant about a "canonical" public chat since chat is a bad medium for long-term documentation and rational discussion - too pithy and ephemeral. I think we would have more success establishing a strong norm of discussing and making decisions through the Github issue / PR / milestone etc. system ([example discussion](https://github.com/cosmos/ics/issues/5#issuecomment-476584809)). Of course chat rooms for questions, implementation assistance, etc. are all fine and require no official approval to create (so by all means).

What do you think?

**Comment by vshvsh** [comment]
I don't think public chats are that bad if there is a tradition to move serious conversations to issues: a place where issues are born so to speak.  Won't argue though, keeping all substance in repo works too. 

The unofficial questions/assistance chat (I suggest Matrix) will need some exposure so that people can actually find it so maybe pin it to community page on Cosmos website or in readme?

**Comment by cwgoes** [comment]
> I don't think public chats are that bad if there is a tradition to move serious conversations to issues: a place where issues are born so to speak. Won't argue though, keeping all substance in repo works too.
> 
> The unofficial questions/assistance chat (I suggest Matrix) will need some exposure so that people can actually find it so maybe pin it to community page on Cosmos website or in readme?

Definitely - if we reinforce that norm, a public chat sounds great. I don't have platform preferences, Matrix is OK with me (that's where a bunch of the other public Cosmos chats are I believe).

**Comment by vshvsh** [comment]
Made it
https://riot.im/app/#/room/#cosmos-ics:matrix.org

**Comment by cwgoes** [comment]
Thanks!
